#ifndef MACROS_H
#define MACROS_H

#include <math.h>

typedef enum {
  EVENT_NONE,
  EVENT_TIMER,
  EVENT_KEYBOARD,
  EVENT_MOUSE,
  // EVENT_SERIAL,
  NUM_EVENTS
} EventType;

// Fonts
#define MAX_FONT_GLYPHS 382

// ESC key
#define ESC_MAKECODE 0x01
#define ESC_BREAKCODE 0x81

// makecodes for arrow keys
#define UP_ARROW 0x48
#define DOWN_ARROW 0X50
#define LEFT_ARROW 0X4B
#define RIGHT_ARROW 0X4D

// breakcodes for arrow keys
#define UP_ARROW_BREAK 0xC8
#define DOWN_ARROW_BREAK 0XD0
#define LEFT_ARROW_BREAK 0XCB
#define RIGHT_ARROW_BREAK 0XCD

// Enter key
#define ENTER_KEY 0x1C
#define ENTER_BREAKCODE 0x9C

#define BACKGROUND_COLOR 0x000000
#define TRANSPARENT 0xFFFFFE

// Game
#define PLAYER_TURN_INCREMENT_DEG 6.0f
#define PLAYER_TURN_INCREMENT_RAD (PLAYER_TURN_INCREMENT_DEG * (M_PI / 180.0f))

#define PLAYER_BASE_SPEED 3.0f

#define PLAYER_ACCELERATION 1.8f
#define PLAYER_DECELERATION 1.5f
#define PLAYER_SKID_DECELERATION 2.0f

#define AI_EASY_BASE_SPEED 2.0f
#define AI_MEDIUM_BASE_SPEED 3.0f
#define AI_HARD_BASE_SPEED 4.0f

#define AI_ACCELERATION 1.8f
#define AI_DECELERATION 1.5f

#define AI_EASY_LOOKAHEAD 40.0f
#define AI_MEDIUM_LOOKAHEAD 60.0f
#define AI_HARD_LOOKAHEAD 80.0f

#define AI_MAX_STEERING_RATE_RAD_PER_SEC (M_PI / 2.0f)

#define AI_EASY_PATH_ADHERENCE 0.6f
#define AI_MEDIUM_PATH_ADHERENCE 0.8f
#define AI_HARD_PATH_ADHERENCE 1.0f

#endif
