#ifndef TILES_H
#define TILES_H

static char * outspace_tile[] = {
   "64 64 1 1",
  "  c #22B14C",
  /* pixels */
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                ",
  "                                                                "
  };

static char * line_tile[] = {
    "64 64 6 1 ",
    "  c #131313",
    ". c #141314",
    "X c #151415",
    "o c #1a1a1a",
    "O c #1a1a1a",
    "+ c #FFFFFF",
    /* pixels */
    "XXXXXXOOXXOOOXXXXOX  XXOOXXOOOOXXXXX.XXXOOX.XXXXXXXXXXXXXXXXOOOX",
    "XXXXXXOXXXOOOOXXXXX  XXOOXXOOOOXXXXXX...XX XXXXXXX.XXXXXXXXXXOOX",
    "XXXXXXX.XOXXXXXX .XXXXXOOOOXXXXOOX.XXXXXXXXXOOXXXX.XXXXXXXXXXOOX",
    "XXXXX..XOOX.XXXXX..X ..XOOOXXXXOX.XOXXXXOXXXOOXXXXXXOX.XXXXXXXOX",
    "X.XOXXXXOOX.XXOOX..OX..XXOOOOXXX.XOXXXX.XXXXXXXXXXXXOXXXXXXX..XX",
    "XXOOXXXXOX..X.XX.. XOX.XXXXXOXXXXOOXXXXXX..XXXXXX...XXX..XXX.XXX",
    "XX..XX.XXXXXXOX.... ......XXX.XX.....XOXX.XXXX.XXX. .  XX.XXXX.X",
    "XXXXXX.XXXXXXOX.... ....X.XXX.XX.....XOXX.XXXX.XXX. .  XX.XXXX.X",
    "XXXOXXXXXXXOXXOX.... ..XXXXX. XX... ..XXOXXXX....XXXOX ..  XXOX.",
    "XXXXXXXXX..XOOOXXXXX...XXXXXX.XX.XXXX..XX.XOOX...XOOX..XX    OX.",
    "XXXXX. XX...XXXXXXX... XOXXXX.XXXOXXX..X..XOOOX...XOXXXXX.   X  ",
    "XXOXX.XOOXXX....XXOXXXX.XXXXXXXXXOXXXXXXXXXXOOOXXX.XXXOXXX   X  ",
    "XXOXXXXXXXXX.XX.XXXXX...++++++++++++++++OXXXXOOXXX....XXXOX.XOOO",
    "XOOXXXXXXXXXXOX.XXXXXXXX++++++++++++++++XXXXXOOXXXXXXX.  XX..OOO",
    "OXXXXOOXXOOXXX..XXXOXXXX++++++++++++++++XXOXXOOOOXXXXOX.  ...XXX",
    "XXXXXOOXXOOXXXXXXXXOXXXX++++++++++++++++XOOX.XOOOXXXXOOXXXXXXXXX",
    "O.XXXXXXXXXOOXXXXXXOOOOO++++++++++++++++XXXOXXXXXXXXXOOOOXXXXOOO",
    "OXXXXXXXXXXOOXXXXXXOOOOO++++++++++++++++XXXXXXX.X.XXXOOOOXXXXOOO",
    "XXXXXXXOOXXOOOOXXOOX  XX++++++++++++++++XOX..X...XXXXXXXXXXXXOOO",
    "XXXXXXXOOXXOOOOXXOOX  XX++++++++++++++++XXX.XXXX..X.XXXXXXXXXXOO",
    "XXXXXXXXXOOXXXXXXXXXXXXX++++++++++++++++XXOXXOOXXXX.XXXXX..XXXOO",
    "XXXXXXXXXOOXXXXXXXXXXXXX++++++++++++++++XOOXXXOXXXX.XX...XXXXXOO",
    "XXXOOXXXXOOXXXXOOXXXOOXX++++++++++++++++XXXXX.XXXXXXXX...XXXXXXX",
    "XXXOOXXXXOOXXXXOOXXXOOXX++++++++++++++++XXXXX.  ....XXX..XXXXXXX",
    "OOOXXOOXXXXXXOOXXXXXXXXX++++++++++++++++XXXOXXOX.XX. ..  XXOOX.X",
    "OOOXXOOXXXXXXOOXXXXXXXXX++++++++++++++++XXXOXXOX..X. ..  XXOOX.X",
    "OXXOOXXXXXXOOXXOOXXXXXXX++++++++++++++++XOXXXXXX....XXX.   XOXXO",
    "XXXXXXXXXXXXXOOOOOXXXXXX++++++++++++++++XXXXOOOX...XOXX. XXXX.XO",
    "XXXXXXXXXXXXXOXXOXXXXXXX++++++++++++++++XXXXXXX.XXXOX....XX XXXX",
    "OXXOOXXOOOOXXXXXXXXOOOXX++++++++++++++++XOXXXXXXXXOX...XXOX XXXX",
    "OXXOOXOOXXOXXXXX.XXXOOXX++++++++++++++++ .. .XOOXXX    XXXX. XXO",
    "OOOOOOOOXXOOOOOX.XXXOOOO++++++++++++++++   .XXOOXXXXXXX    .  XO",
    "OOXXOOXXOOOOXXOXXOXXOXXX++++++++++++++++ XXXXXXXXXXXOXX .     .O",
    "XXXXOOXXOOOOXXOXOOXXOXXX++++++++++++++++XXXXX..XXXXXOXX.X    ..O",
    "OOXOOOOOOOXXXXX.XXXXXOOX++++++++++++++++X.  OO.XXXXXXXXX..XXXXXX",
    "XXXXXXXXOOOOXXOOXXXXXXXX++++++++++++++++X.  XX. XXXXXXXXOO.XXXXX",
    "XXXXXXXXOOOOXXOOXXXXXXXX++++++++++++++++OXX.XXXXXXXX.   XOX.XXOX",
    "OOXXOOOOOOXXOOOOXXXXOXXX++++++++++++++++OOXXOOXXXXOOX   .X  .XOX",
    "OOXXOOOOOOXXOOOOXXXXOXXX++++++++++++++++XXXXXXXXXX..X.  .X  X X.",
    "XXOOXXXXOOXXXXXXXXOOXXXX++++++++++++++++XXXXXXXXXX..XX.X.XXX    ",
    "XXOOXXXXOOXXXXXXOOOOXXX.++++++++++++++++XXXXXXXXXX..XOOX.X..  X ",
    "XXOOXXXXXXXXXXOOOXXXXX..++++++++++++++++ XXX..XXXX.. XX. .XOXXOX",
    "XXOOXXXXXXXXXXOOXXXXXXXX++++++++++++++++ X..XXOO.... ...  XX.XXX",
    "OOXXXXOOXXOOXXXXXXXXOXXX++++++++++++++++..XXXXOOXX   .XX.....XX.",
    "OOXXXXOOXXOOXXXXXXXXOXXX++++++++++++++++..XXXXXXOO    ...XX.... ",
    "OOXXXXXXXXXXOOXXXXXXOOOO++++++++++++++++X...XXOOXXXX  ..XOX...XX",
    "OOXXXXXXXXXXXXXXXXXXXOOO++++++++++++++++X...XXOOXXXXX...XOX...XX",
    "XXXXXXXXOOXXXXOOXXOOX  X++++++++++++++++XXXX......XXXXXXXXXXXXOO",
    "XXXX..XXOOXXXXXXXXOOX  X++++++++++++++++XXXX    ..XXXXXX  XXXXOO",
    "XXXXXXXXXXOO..XXXXXXXX.X++++++++++++++++OXOOXXOOXXXXXXXXXXXXXXXO",
    "XXXXXXXX..OOXXXXXX  .XXX++++++++++++++++OXOOXXOO....XXXXXX..XXXO",
    "XX..OOXX..OOXXXXOX.. OOXXXXXXXXXX  XXXXXXXXXXXXXXX  XXXXXXXXXXXX",
    "XXXXOOXX..XX....XOX. XXXXXXOOOOXX  OO...XXXXXXXX      XXXXXXXXX.",
    "XXXXXXOO..XX..XX ... XXXX..XXXX..  XX. XXX..OOXX  ..XX  X XXXOOX",
    "XXXXXXOO..XX..XX ... XXXX..XXXX..  XX. XXX..OOXX  ..XX    XXXOOX",
    "XXXXOOXXXXXXXX..OX.....XXXXXXXX  ..XXX.XXXXXXXXXXX  ..    X.XXXO",
    "XXXXXXXXXXXX..XXOXX..XXXXXXXXXX..XXOOXX.XX..XXOOXX  XX  ..X....O",
    "..X.XXXXXXXXXXOOXX...XXXXXXXXXXXXXXOOXX .XXXXXXXXXXXXX..  .  XXO",
    "XX..OOXXXXXXXXXX....XOOXXXXXXOOXXXXOOXXXXXOOXXXXOOOO..    X  XOO",
    "XXXXXXXXXXOOXXXX  ..XXX..XXXXOOOOXX  XX...OOXXXXXXXX  XXXXOOX.XO",
    "XXXXXXXXXXOOXXXX  XXXXXXXXXXXXXOOOO  OXXX.XXXXXXXXXXXXOO...XX..O",
    "XXOOXXOOXXXXXXXXXXXXX    XXXXXXXXOOXXXOOX.XXOOXXXXOOXXXX..  .  O",
    "XXOOXXOOXXXXXXXOXXXXX    XXOOXXXXOOXXXOOXXOOOO.XXXOOXXXXXXXXXXXO",
    "XXXXXXXXOOXXXXXXXXXXOOOOOXXXXXXOOXXOOXXXOOOOXXXXXXOOOOXXXXOOOXXO"
  };

static char * track_tile[] = {
    "64 64 5 1 ",
    "  c #131313",
    ". c #141314",
    "X c #151415",
    "o c #1a1a1a",
    "O c #1a1a1a",
    /* pixels */
    "XXXXXXOOXXOOOXXXXOX  XXOOXXOOOOXXXXX.XXXOOX.XXXXXXXXXXXXXXXXOOOX",
    "XXXXXXOXXXOOOOXXXXX  XXOOXXOOOOXXXXXX...XX XXXXXXX.XXXXXXXXXXOOX",
    "XXXXXXX.XOXXXXXX .XXXXXOOOOXXXXOOX.XXXXXXXXXOOXXXX.XXXXXXXXXXOOX",
    "XXXXX..XOOX.XXXXX..X ..XOOOXXXXOX.XOXXXXOXXXOOXXXXXXOX.XXXXXXXOX",
    "X.XOXXXXOOX.XXOOX..OX..XXOOOOXXX.XOXXXX.XXXXXXXXXXXXOXXXXXXX..XX",
    "XXOOXXXXOX..X.XX.. XOX.XXXXXOXXXXOOXXXXXX..XXXXXX...XXX..XXX.XXX",
    "XX..XX.XXXXXXOX.... ......XXX.XX.....XOXX.XXXX.XXX. .  XX.XXXX.X",
    "XXXXXX.XXXXXXOX.... ....X.XXX.XX.....XOXX.XXXX.XXX. .  XX.XXXX.X",
    "XXXOXXXXXXXOXXOX.... ..XXXXX. XX... ..XXOXXXX....XXXOX ..  XXOX.",
    "XXXXXXXXX..XOOOXXXXX...XXXXXX.XX.XXXX..XX.XOOX...XOOX..XX    OX.",
    "XXXXX. XX...XXXXXXX... XOXXXX.XXXOXXX..X..XOOOX...XOXXXXX.   X  ",
    "XXOXX.XOOXXX....XXOXXX..XXXXXXXXXOXXXXXXXXXXOOOXXX.XXXOXXX   X  ",
    "XXOXXXXXXXXX.XX.XXXXX.....XXXXOXXOOXXX  OXXXXOOXXX....XXXOX.XOOO",
    "XOOXXXXXXXXXXOX.XXXXXXXXX.XXXXOOOXXOOO  XXXXXOOXXXXXXX.  XX..OOO",
    "OXXXXOOXXOOXXX..XXXOXXXX    .XOOXXXXOOXXXXOXXOOOOXXXXOX.  ...XXX",
    "XXXXXOOXXOOXXXXXXXXOXXXX    X.OOXXXXOOXXXOOX.XOOOXXXXOOXXXXXXXXX",
    "O.XXXXXXXXXOOXXXXXXOOOOOOOOOXXXXXXOOXXOOXXXOXXXXXXXXXOOOOXXXXOOO",
    "OXXXXXXXXXXOOXXXXXXOOOOOOOOOXXXXXXOOXXOOXXXXXXX.X.XXXOOOOXXXXOOO",
    "XXXXXXXOOXXOOOOXXOOX  XXOOXXOOOOXXXXXXXXXOX..X...XXXXXXXXXXXXOOO",
    "XXXXXXXOOXXOOOOXXOOX  XXOOXXOOOOXXXXXXXXXXX.XXXX..X.XXXXXXXXXXOO",
    "XXXXXXXXXOOXXXXXXXXXXXXXOOOOXXXXOOXXOOOOXXOXXOOXXXX.XXXXX..XXXOO",
    "XXXXXXXXXOOXXXXXXXXXXXXXOOOOXXXXOOX.OOXXXOOXXXOXXXX.XX...XXXXXOO",
    "XXXOOXXXXOOXXXXOOXXXOOXXXXOOOOXXXXXXXXXXXXXXX.XXXXXXXX...XXXXXXX",
    "XXXOOXXXXOOXXXXOOXXXOOXXXXOOOX..XXOOXXXXXXXXX.  ....XXX..XXXXXXX",
    "OOOXXOOXXXXXXOOXXXXXXXXXXXX....    ...XXXXXOXXOX.XX. ..  XXOOX.X",
    "OOOXXOOXXXXXXOOXXXXXXXXXXXX....    ...XXXXXOXXOX..X. ..  XXOOX.X",
    "OXXOOXXXXXXOOXXOOXXXXXXXOOXXXXX.XXXX.  XXOXXXXXX....XXX.   XOXXO",
    "XXXXXXXXXXXXXOOOOOXXXXXXOOXXXXXXXXXXXX .XXXXOOOX...XOXX. XXXX.XO",
    "XXXXXXXXXXXXXOXXOXXXXXXXOOXXXXX...OO.   XXXXXXX.XXXOX....XX XXXX",
    "OXXOOXXOOOOXXXXXXXXOOOXXXXXXOOOX..OO.  .XOXXXXXXXXOX...XXOX XXXX",
    "OXXOOXOOXXOXXXXX.XXXOOXXXXXXOOOX..OX  XX .. .XOOXXX    XXXX. XXO",
    "OOOOOOOOXXOOOOOX.XXXOOOOOOXXXXOXXXXX..XX   .XXOOXXXXXXX    .  XO",
    "OOXXOOXXOOOOXXOXXOXXOXXXXOXXXXOXXX .X.XX XXXXXXXXXXXOXX .     .O",
    "XXXXOOXXOOOOXXOXOOXXOXXXXOOOOOXXXX.XX.XXXXXXX..XXXXXOXX.X    ..O",
    "OOXOOOOOOOXXXXX.XXXXXOOXXXXXXOXXOOXXX..XX.  OO.XXXXXXXXX..XXXXXX",
    "XXXXXXXXOOOOXXOOXXXXXXXXXXXOOXXOOX. ...XX.  XX. XXXXXXXXOO.XXXXX",
    "XXXXXXXXOOOOXXOOXXXXXXXXXXXOOXXXX...  .XOXX.XXXXXXXX.   XOX.XXOX",
    "OOXXOOOOOOXXOOOOXXXXOXXXXXXOOXXXX... ..XOOXXOOXXXXOOX   .X  .XOX",
    "OOXXOOOOOOXXOOOOXXXXOXXXXXXOOX.OX.XXXX.XXXXXXXXXXX..X.  .X  X X.",
    "XXOOXXXXOOXXXXXXXXOOXXXXXOOXXXXX.XXXXX.XXXXXXXXXXX..XX.X.XXX    ",
    "XXOOXXXXOOXXXXXXOOOOXXX..OOXXXXX.XXXXXXXXXXXXXXXXX..XOOX.X..  X ",
    "XXOOXXXXXXXXXXOOOXXXXX...XXXXXXXXXXXOOX  XXX..XXXX.. XX. .XOXXOX",
    "XXOOXXXXXXXXXXOOXXXXXXXXXXXXXXXOXXOOXXO  X..XXOO.... ...  XX.XXX",
    "OOXXXXOOXXOOXXXXXXXXOXXXX      OXXXX.XOX..XXXXOOXX   .XX.....XX.",
    "OOXXXXOOXXOOXXXXXXXXOXXXX    XXXX  XXOX...XXXXXXOO    ...XX.... ",
    "OOXXXXXXXXXXOOXXXXXXOOOOOOOOOXXX.  XXXXXX...XXOOXXXX  ..XOX...XX",
    "OOXXXXXXXXXXXXXXXXXXXOOOOOOOOXXX   XXXXXX...XXOOXXXXX...XOX...XX",
    "XXXXXXXXOOXXXXOOXXOOX  XXOOXXOOOOXXXXXXXXXXX......XXXXXXXXXXXXOO",
    "XXXX..XXOOXXXXXXXXOOX  XXOOXXOOXXXXXXX  XXXX    ..XXXXXX  XXXXOO",
    "XXXXXXXXXXOO..XXXXXXXX.XXOOOOXXXXXXXXXXXOXOOXXOOXXXXXXXXXXXXXXXO",
    "XXXXXXXX..OOXXXXXX  .XXXXOOOOXXXXXX..OXXOXOOXXOO....XXXXXX..XXXO",
    "XX..OOXX..OOXXXXOX.. OOXXXXXXXXXX  XXXXXXXXXXXXXXX  XXXXXXXXXXXX",
    "XXXXOOXX..XX....XOX. XXXXXXOOOOXX  OO...XXXXXXXX      XXXXXXXXX.",
    "XXXXXXOO..XX..XX ... XXXX..XXXX..  XX. XXX..OOXX  ..XX  X XXXOOX",
    "XXXXXXOO..XX..XX ... XXXX..XXXX..  XX. XXX..OOXX  ..XX    XXXOOX",
    "XXXXOOXXXXXXXX..OX.....XXXXXXXX  ..XXX.XXXXXXXXXXX  ..    X.XXXO",
    "XXXXXXXXXXXX..XXOXX..XXXXXXXXXX..XXOOXX.XX..XXOOXX  XX  ..X....O",
    "..X.XXXXXXXXXXOOXX...XXXXXXXXXXXXXXOOXX .XXXXXXXXXXXXX..  .  XXO",
    "XX..OOXXXXXXXXXX....XOOXXXXXXOOXXXXOOXXXXXOOXXXXOOOO..    X  XOO",
    "XXXXXXXXXXOOXXXX  ..XXX..XXXXOOOOXX  XX...OOXXXXXXXX  XXXXOOX.XO",
    "XXXXXXXXXXOOXXXX  XXXXXXXXXXXXXOOOO  OXXX.XXXXXXXXXXXXOO...XX..O",
    "XXOOXXOOXXXXXXXXXXXXX    XXXXXXXXOOXXXOOX.XXOOXXXXOOXXXX..  .  O",
    "XXOOXXOOXXXXXXXOXXXXX    XXOOXXXXOOXXXOOXXOOOO.XXXOOXXXXXXXXXXXO",
    "XXXXXXXXOOXXXXXXXXXXOOOOOXXXXXXOOXXOOXXXOOOOXXXXXXOOOOXXXXOOOXXO"
  };

static char * left_line_tile[] = {
    "64 64 7 1 ",
    "  c #131213",
    ". c #141214",
    "X c #151515",
    "o c #181818",
    "O c #635F63",
    "+ c #22B14C",
    "@ c #FFFFFF",
    /* pixels */
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOooX.XXXX@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOXX XXXXX@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOXXXXooXX@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOoXXXooXX@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOXXXXXXXX@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOX..XXXXX@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOX.XXXX.X@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOX.XXXX.X@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOoXXXX...@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOX.XooXX.@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOO.XXoooX.@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOXXXXoooX@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOoXXXXooX@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOXXXXXooX@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOXXoXXooo@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOXooX.Xoo@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOXXXoXXXX@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOXXXXXXX.@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOXoX..X..@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOXXX.XXXX@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOXooXXooX@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOXooX.XoX@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOXXXX..XX@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOXXXX..  @@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOXXooXXoX@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOXXooXXoX@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOXooXXXXX@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOXXXooooX@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOXXXXXXX.@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOXoXXXXXX@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOO .. .Xoo@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOO   .XXoo@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOO XXXXXXX@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOXXXXX..X@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOX.  oo.X@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOX.  XX. @@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOoX..XXXX@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOooXXooXX@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOXXXXXXXX@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOX.XXXXXX@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOXXXXXXXX@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOO XXX..XX@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOO X..XXoo@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOO..XXXXoo@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOO..XXXXoo@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOX...XXoo@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOX...XXoo@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOXXXX....@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOXXXX    @@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOoXooXXoo@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOoXooXXoo@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOXXXXXXXX@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOoXXXXXXX@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOXX..ooXX@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOXXX.ooXX@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOXXXXXXXX@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOXX..XXoo@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOO.XXXXXXX@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOXXooXXoo@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOO..ooXXXX@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOX.XXXXXX@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOX.XXooXX@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOXXooooXX@@@@@@@@@@@@@@@@",
    "++++++++++++++++++++++++OOOOOOOOOOOOOOOOooooXXXX@@@@@@@@@@@@@@@@"
  };

static char * right_line_tile[] = {
  "64 64 8 1 ",
  "  c #131213",
  ". c #141314",
  "X c #151415",
  "o c #1A1A1A",
  "O c #1A1A1A",
  "+ c #635F63",
  "@ c #22B14C",
  "# c #FFFFFF",
  /* pixels */
  "################XXXXOOOO++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################..OOOOXX++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################XXOOXX.X++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################XXXXXX.X++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################XXXXOO..++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################XXXXOOXX++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################XXXXXXXX++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################OOXX.XXX++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################XXXXXXXX++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################XXOO...X++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################XXOO...X++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################XXXXXXXX++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################XXXXXXXX++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################OOXXOOXO++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################OOXXOOXO++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################    XXXX++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################..XXXXXX++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################OOXX...X++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################OOXX...X++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################XXXXXX..++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################OOXXXX..++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################OOXX..X ++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################XX..XXX ++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################XXXXXXXX++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################XXXXXX.X++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################XXXXXXXX++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################XXOOXXOO++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################XXXX..XO++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################ .XX  .X++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################X.OO  .X++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################X..XXXXX++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################XXXXXXX ++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################OOXX.   ++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################OOX. .. ++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################XXXXXXOX++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################.XXXXXXX++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################XOOOXXXX++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################XXXXXXOX++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################XOXXOXXX++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################XOXXOXXX++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################  ..XXXX++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################XX..XXXX++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################XOXXXOOX++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################XOOXXOXX++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################XXXX.XXX++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################XXXX.XOX++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################.XXXXXXX++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################XXXXOXXX++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################OOX.XOOX++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################OOOXXOXX++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################XOOXXXXX++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################XOOXXXXO++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################XOOOXXXX++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################XXOOOXX.++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################..XOOX.X++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################...XXXXO++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################X.XXXXXX++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################X.XXXX.X++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################XXXXX..X++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################XXXXXXXX++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################XXOOXXXO++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################XXOOXXXX++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################XXXXX XX++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@",
  "################XXXX.XOO++++++++++++++++@@@@@@@@@@@@@@@@@@@@@@@@"
};

#endif //TILES_H

